-- NEWMUX OS: database setup for a brand-new, empty Supabase project.
--
-- Generated by `npm run db:supabase-sql` from db/migrations/*.sql. Do not edit it
-- by hand; add a migration and regenerate instead.
--
-- Use: Supabase dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
-- If the editor warns about a "destructive" query (migration 0010 drops a table
-- that was just created) choose "Run this query". Run it once, on an empty database.
-- It creates the tables only; the first login is created separately
-- (docs/DEPLOY_CLOUDFLARE.md, "Create your login").

create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());

-- ===== 0001_core.sql =====
begin;
-- NEWMUX OS — core entities: users, clients (companies), contacts, products,
-- payout parties, deduction types, ventures.
-- gen_random_uuid() is built into Postgres 13+, no extension needed.

create type user_role as enum ('partner_admin', 'lead_dev');
create type billing_cycle as enum ('monthly', 'quarterly', 'annual');

create table users (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  full_name text not null,
  role user_role not null default 'lead_dev',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create sequence client_code_seq;

create table clients (
  id uuid primary key default gen_random_uuid(),
  client_code text unique not null default ('CL-' || lpad(nextval('client_code_seq')::text, 3, '0')),
  name text not null,
  industry text,
  website text,
  email text,
  phone text,
  billing_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table contacts (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete cascade,
  full_name text not null,
  title text,
  email text,
  phone text,
  whatsapp text,
  is_primary boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_contacts_client on contacts(client_id);

create table products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  is_saas boolean not null default false,
  paddle_product_id text unique,
  created_at timestamptz not null default now()
);

-- Payout parties in a profit split (PRD 5.3) — not login users.
create table parties (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table deduction_types (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  kind text not null check (kind in ('fixed', 'percentage')),
  created_at timestamptz not null default now()
);

-- Ventures personally held by the founders (PRD 14).
create table ventures (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  brand_description text,
  website_url text,
  launch_status text not null default 'planning'
    check (launch_status in ('planning', 'in_development', 'launched', 'paused')),
  profit_split_rule_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into schema_migrations (name) values ('0001_core.sql');
commit;

-- ===== 0002_work.sql =====
begin;
-- Projects, tasks (with subtasks + comments), meetings, profit-split rules.

create type project_status as enum ('planning', 'active_sprint', 'paused', 'completed', 'archived');
create type task_priority as enum ('urgent', 'high', 'medium', 'low');
create type task_status as enum ('todo', 'in_progress', 'in_review', 'done');

create table projects (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete set null,
  product_id uuid references products(id) on delete set null,
  name text not null,
  description text,
  color text not null default 'blue',
  status project_status not null default 'planning',
  started_at date,
  target_end_at date,
  created_by uuid references users(id) on delete set null,
  -- Technical detail (PRD 10.2). Credentials live in the vault, never here.
  tech_stack text,
  hosting_provider text,
  control_panel_url text,
  domain text,
  domain_renewal_date date,
  github_url text,
  profit_split_rule_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_projects_client on projects(client_id);

-- Fully editable in Settings (PRD 5.3.1). splits: [{partyId, percentageBps}],
-- deductions: [{deductionTypeId, value}] (fixed → minor units, percentage → bps).
create table profit_split_rules (
  id uuid primary key default gen_random_uuid(),
  scope_type text not null check (scope_type in ('project', 'venture')),
  scope_id uuid not null,
  splits jsonb not null default '[]',
  deductions jsonb not null default '[]',
  is_default boolean not null default false,
  updated_by uuid references users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (scope_type, scope_id)
);

alter table projects
  add constraint projects_profit_split_rule_fk
  foreign key (profit_split_rule_id) references profit_split_rules(id) on delete set null;
alter table ventures
  add constraint ventures_profit_split_rule_fk
  foreign key (profit_split_rule_id) references profit_split_rules(id) on delete set null;

create table tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  title text not null,
  description text,
  priority task_priority not null default 'medium',
  status task_status not null default 'todo',
  assignee_id uuid references users(id) on delete set null,
  due_at date,
  sort_order int not null default 0,
  completed_at timestamptz,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_tasks_project on tasks(project_id);
create index idx_tasks_assignee on tasks(assignee_id);

create table subtasks (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tasks(id) on delete cascade,
  title text not null,
  done boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create index idx_subtasks_task on subtasks(task_id);

create table task_comments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references tasks(id) on delete cascade,
  author_id uuid references users(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now()
);
create index idx_task_comments_task on task_comments(task_id);

create table meetings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  starts_at timestamptz not null,
  duration_minutes int not null default 60,
  location text,
  linked_project_id uuid references projects(id) on delete set null,
  linked_client_id uuid references clients(id) on delete set null,
  notes text,
  recurring text not null default 'none' check (recurring in ('none', 'weekly', 'monthly')),
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_meetings_starts on meetings(starts_at);
insert into schema_migrations (name) values ('0002_work.sql');
commit;

-- ===== 0003_finance.sql =====
begin;
-- Documents (quotes/contracts/invoices), payments, expenses, hosting fees, audit log.

create type document_type as enum ('quote', 'contract', 'invoice');
create type document_status as enum ('draft', 'sent', 'accepted', 'signed', 'paid', 'archived');

-- Atomic per-type, per-year numbering (QUO-2026-2607, INV-2026-0266 …).
create table doc_sequences (
  doc_type document_type not null,
  year int not null,
  last_value int not null,
  primary key (doc_type, year)
);

create table documents (
  id uuid primary key default gen_random_uuid(),
  type document_type not null,
  status document_status not null default 'draft',
  client_id uuid not null references clients(id) on delete restrict,
  product_id uuid references products(id) on delete set null,
  project_id uuid references projects(id) on delete set null,
  converted_from_quotation_id uuid references documents(id) on delete set null,
  profit_split_rule_id uuid references profit_split_rules(id) on delete set null,
  document_number text unique not null,
  currency text not null default 'BHD' check (currency in ('BHD', 'USD')),
  subtotal_cents bigint not null default 0,
  tax_rate_bps int not null default 0,
  tax_cents bigint not null default 0,
  total_cents bigint not null default 0,
  payment_terms text,
  notes text,
  issued_at timestamptz,
  due_at date,
  accepted_at timestamptz,
  paid_at timestamptz,
  archived_at timestamptz,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_documents_client on documents(client_id);
create index idx_documents_project on documents(project_id);
create index idx_documents_type_status on documents(type, status);

create table document_line_items (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  description text not null,
  quantity numeric(12, 3) not null default 1,
  unit_price_cents bigint not null default 0,
  sort_order int not null default 0
);
create index idx_line_items_document on document_line_items(document_id);

create table document_status_history (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  from_status document_status,
  to_status document_status not null,
  changed_by uuid references users(id) on delete set null,
  changed_at timestamptz not null default now()
);
create index idx_status_history_document on document_status_history(document_id);

-- Partial/full payments. Never changes the invoice's value (PRD 5.5).
create table payments (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  amount_cents bigint not null check (amount_cents > 0),
  paid_on date not null default current_date,
  method text not null check (method in ('cash', 'transfer', 'card', 'cheque')),
  reference text,
  recorded_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_payments_document on payments(document_id);
create index idx_payments_paid_on on payments(paid_on);

create table recurring_expenses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  amount_cents bigint not null,
  currency text not null check (currency in ('BHD', 'USD')),
  cycle billing_cycle not null,
  last_payment_date date,
  next_due_date date,
  linked_client_id uuid references clients(id) on delete set null,
  linked_project_id uuid references projects(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'paused')),
  created_at timestamptz not null default now()
);

-- Money actually spent (one-off, or a logged payment of a recurring expense).
create table expenses (
  id uuid primary key default gen_random_uuid(),
  description text not null,
  category text not null,
  vendor text,
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null check (currency in ('BHD', 'USD')),
  spent_on date not null default current_date,
  linked_client_id uuid references clients(id) on delete set null,
  linked_project_id uuid references projects(id) on delete set null,
  recurring_expense_id uuid references recurring_expenses(id) on delete set null,
  notes text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_expenses_spent_on on expenses(spent_on);

-- Hosting/domain fees collected FROM clients (PRD 6).
create table hosting_subscriptions (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  project_id uuid references projects(id) on delete set null,
  item text not null check (item in ('server', 'domain', 'other')),
  label text,
  amount_cents bigint not null,
  currency text not null check (currency in ('BHD', 'USD')),
  cycle billing_cycle not null,
  last_collected_date date,
  next_due_date date,
  status text not null default 'active' check (status in ('active', 'overdue', 'paused')),
  linked_invoice_id uuid references documents(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Every change to money-affecting records (PRD 15.1).
create table audit_log (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null,
  entity_id uuid not null,
  action text not null check (action in ('create', 'update', 'delete')),
  summary text not null,
  changed_by uuid references users(id) on delete set null,
  changed_at timestamptz not null default now()
);
create index idx_audit_changed_at on audit_log(changed_at desc);
insert into schema_migrations (name) values ('0003_finance.sql');
commit;

-- ===== 0004_crm.sql =====
begin;
-- CRM: deals pipeline and the activity timeline (calls, emails, notes, follow-ups).

create type deal_stage as enum ('lead', 'qualified', 'proposal', 'negotiation', 'won', 'lost');
create type activity_kind as enum ('call', 'email', 'meeting', 'note', 'whatsapp', 'follow_up');

create table deals (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  client_id uuid references clients(id) on delete set null,
  contact_id uuid references contacts(id) on delete set null,
  stage deal_stage not null default 'lead',
  value_cents bigint not null default 0,
  currency text not null default 'BHD' check (currency in ('BHD', 'USD')),
  probability int not null default 10 check (probability between 0 and 100),
  expected_close date,
  owner_id uuid references users(id) on delete set null,
  source text,
  notes text,
  lost_reason text,
  sort_order int not null default 0,
  project_id uuid references projects(id) on delete set null,
  won_at timestamptz,
  closed_at timestamptz,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_deals_stage on deals(stage);
create index idx_deals_client on deals(client_id);

create table activities (
  id uuid primary key default gen_random_uuid(),
  kind activity_kind not null,
  subject text not null,
  body text,
  client_id uuid references clients(id) on delete cascade,
  contact_id uuid references contacts(id) on delete set null,
  deal_id uuid references deals(id) on delete cascade,
  due_at timestamptz,
  completed_at timestamptz,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_activities_client on activities(client_id);
create index idx_activities_deal on activities(deal_id);
create index idx_activities_due on activities(due_at) where completed_at is null;

alter table documents add column deal_id uuid references deals(id) on delete set null;
alter table meetings add column linked_deal_id uuid references deals(id) on delete set null;
insert into schema_migrations (name) values ('0004_crm.sql');
commit;

-- ===== 0005_kb.sql =====
begin;
-- Knowledge base: spaces → nested pages (TipTap JSON), templates, favorites, recents.

create table kb_spaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  icon text not null default 'book',
  color text not null default 'blue',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table kb_pages (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references kb_spaces(id) on delete cascade,
  parent_id uuid references kb_pages(id) on delete cascade,
  title text not null default '',
  emoji text,
  content jsonb not null default '{"type":"doc","content":[]}',
  content_text text not null default '',
  search tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(content_text, '')), 'B')
  ) stored,
  client_id uuid references clients(id) on delete set null,
  project_id uuid references projects(id) on delete set null,
  deal_id uuid references deals(id) on delete set null,
  is_template boolean not null default false,
  sort_order int not null default 0,
  created_by uuid references users(id) on delete set null,
  updated_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_kb_pages_space on kb_pages(space_id);
create index idx_kb_pages_parent on kb_pages(parent_id);
create index idx_kb_pages_search on kb_pages using gin(search);

create table kb_favorites (
  user_id uuid not null references users(id) on delete cascade,
  page_id uuid not null references kb_pages(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, page_id)
);

create table kb_page_views (
  user_id uuid not null references users(id) on delete cascade,
  page_id uuid not null references kb_pages(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (user_id, page_id)
);

alter table meetings add column kb_page_id uuid references kb_pages(id) on delete set null;
insert into schema_migrations (name) values ('0005_kb.sql');
commit;

-- ===== 0006_ops.sql =====
begin;
-- Vault, SaaS billing (Paddle), growth campaigns, company profile, BD pipeline, settings.

create type secret_type as enum ('api_token', 'db_connection', 'deploy_key', 'ssh_login', 'other');
create type saas_subscription_status as enum ('trialing', 'active', 'past_due', 'canceled', 'paused');
create type campaign_channel as enum ('meta_ads', 'linkedin', 'google_search', 'outbound_email');

create table vault_master_config (
  id int primary key default 1 check (id = 1),
  kdf_salt bytea not null,
  passphrase_verifier bytea not null,
  created_at timestamptz not null default now()
);

create table secrets_vault (
  id uuid primary key default gen_random_uuid(),
  client_id uuid references clients(id) on delete cascade,
  project_id uuid references projects(id) on delete cascade,
  label text not null,
  secret_type secret_type not null,
  ciphertext bytea not null,
  iv bytea not null,
  auth_tag bytea not null,
  masked_preview text not null,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table vault_access_log (
  id uuid primary key default gen_random_uuid(),
  secret_id uuid,
  accessed_by uuid references users(id) on delete set null,
  action text not null,
  accessed_at timestamptz not null default now()
);

create table saas_customers (
  id uuid primary key default gen_random_uuid(),
  paddle_customer_id text unique not null,
  client_id uuid references clients(id) on delete set null,
  email text
);

create table saas_subscriptions (
  id uuid primary key default gen_random_uuid(),
  paddle_subscription_id text unique not null,
  saas_customer_id uuid not null references saas_customers(id) on delete cascade,
  product_id uuid references products(id) on delete set null,
  status saas_subscription_status not null,
  currency text not null default 'USD',
  recurring_amount_cents bigint not null default 0,
  billing_interval text not null check (billing_interval in ('month', 'year')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  trial_ends_at timestamptz,
  canceled_at timestamptz
);

create table saas_transactions (
  id uuid primary key default gen_random_uuid(),
  paddle_transaction_id text unique not null,
  saas_subscription_id uuid references saas_subscriptions(id) on delete set null,
  saas_customer_id uuid references saas_customers(id) on delete set null,
  amount_cents bigint not null,
  currency text not null,
  status text not null,
  billed_at timestamptz
);

create table paddle_webhook_events (
  event_id text primary key,
  processed_at timestamptz not null default now()
);

create table campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  channel campaign_channel not null,
  product_id uuid references products(id) on delete set null,
  start_date date,
  end_date date,
  is_active boolean not null default true,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table campaign_metrics (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references campaigns(id) on delete cascade,
  metric_date date not null,
  spend_cents bigint not null default 0,
  leads_captured int not null default 0,
  conversions int not null default 0,
  revenue_cents bigint not null default 0,
  unique (campaign_id, metric_date)
);

create table company_profile (
  id int primary key default 1 check (id = 1),
  legal_name text not null default 'NEWMUX',
  cr_number text not null default '',
  cr_renewal_date date,
  main_domain text not null default '',
  main_domain_renewal_date date,
  vat_number text,
  address text,
  phone text,
  email text
);

create table certifications (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  status text not null check (status in ('active', 'pending', 'expired')),
  expiry_date date,
  created_at timestamptz not null default now()
);

create table partnerships (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table pipeline_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  stage text not null default 'in_progress' check (stage in ('in_progress', 'complete')),
  notes text,
  created_at timestamptz not null default now()
);

-- Small key/value store for app-wide settings (e.g. migration checklist state).
create table app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into schema_migrations (name) values ('0006_ops.sql');
commit;

-- ===== 0007_rls.sql =====
begin;
-- The app talks to Postgres only from the server, as the table owner, and
-- enforces access in lib/rbac.ts. Enabling RLS with NO policies means the
-- Supabase REST/anon/authenticated roles can read or write nothing at all.
do $$
declare t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end $$;
insert into schema_migrations (name) values ('0007_rls.sql');
commit;

-- ===== 0008_finance_core.sql =====
begin;
-- Finance core (Improvements PRD, items 1–6): bank accounts with an opening
-- balance and statement reconciliation, partner payouts, funds (the Newmux
-- reserve), ordered deductions with an explicit base, invoice-level split
-- rules, and expenses that can be charged to one invoice.

-- 1. Company bank accounts. The running balance is the opening balance plus
--    every movement dated on or after opening_balance_date.
create table bank_accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  currency text not null default 'BHD' check (currency in ('BHD', 'USD')),
  opening_balance_cents bigint not null default 0,
  opening_balance_date date not null,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- At most one default account: payments and expenses without an account land there.
create unique index bank_accounts_one_default on bank_accounts (is_default) where is_default;

-- A check against a bank statement. A non-zero adjustment is posted as a
-- movement on the statement date, so the balance then matches the bank.
create table bank_reconciliations (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references bank_accounts(id) on delete cascade,
  statement_date date not null,
  statement_balance_cents bigint not null,
  computed_balance_cents bigint not null,
  adjustment_cents bigint not null default 0,
  note text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_reconciliations_account on bank_reconciliations(account_id, statement_date desc);

alter table payments add column account_id uuid references bank_accounts(id) on delete set null;
alter table expenses add column account_id uuid references bank_accounts(id) on delete set null;

-- 6. A party is a partner or a fund (the Newmux reserve). A deduction type
--    can credit a fund, and an expense can be charged to one (spending it).
alter table parties add column kind text not null default 'partner' check (kind in ('partner', 'fund'));
alter table deduction_types add column fund_party_id uuid references parties(id) on delete set null;
alter table expenses add column fund_party_id uuid references parties(id) on delete set null;

-- 2. What was actually paid to each party.
create table payouts (
  id uuid primary key default gen_random_uuid(),
  party_id uuid not null references parties(id) on delete restrict,
  type text not null check (type in ('share', 'advance', 'withdrawal', 'reimbursement')),
  amount_cents bigint not null check (amount_cents > 0),
  currency text not null default 'BHD' check (currency in ('BHD', 'USD')),
  paid_on date not null,
  document_id uuid references documents(id) on delete set null,
  account_id uuid references bank_accounts(id) on delete set null,
  reference text,
  notes text,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index idx_payouts_party on payouts(party_id);
create index idx_payouts_paid_on on payouts(paid_on);

-- 5. A split rule can belong to a single invoice (an override of the project's rule).
alter table profit_split_rules drop constraint profit_split_rules_scope_type_check;
alter table profit_split_rules add constraint profit_split_rules_scope_type_check
  check (scope_type in ('project', 'venture', 'document'));

-- 3/4. Pass-through costs: an expense charged to one invoice comes off that
--      invoice before any percentage deduction.
alter table expenses add column document_id uuid references documents(id) on delete set null;
create index idx_expenses_project on expenses(linked_project_id);
create index idx_expenses_document on expenses(document_id);

-- 17. Expenses keep their BHD value at the payment date's rate, so BHD totals
--     can't drift. Existing rows get the official peg (1 BHD = 2.6596 USD).
alter table expenses add column fx_rate numeric(12, 6);
alter table expenses add column amount_bhd_cents bigint;
update expenses set fx_rate = 1, amount_bhd_cents = amount_cents where currency = 'BHD';
update expenses set fx_rate = round(1 / 2.6596, 6), amount_bhd_cents = round(amount_cents * 10 / 2.6596) where currency = 'USD';
-- Any insert that doesn't say (seed data, older code paths) gets the peg.
create function expenses_fill_bhd() returns trigger language plpgsql as $$
begin
  if new.amount_bhd_cents is null then
    new.amount_bhd_cents := case when new.currency = 'BHD' then new.amount_cents else round(new.amount_cents * 10 / 2.6596) end;
    new.fx_rate := case when new.currency = 'BHD' then 1 else round(1 / 2.6596, 6) end;
  end if;
  return new;
end $$;
create trigger expenses_fill_bhd before insert or update on expenses for each row execute function expenses_fill_bhd();
alter table expenses alter column amount_bhd_cents set not null;

-- The reserve fund, and the deduction types that feed it.
insert into parties (name, kind)
select 'Newmux Reserve', 'fund'
where not exists (select 1 from parties where kind = 'fund');

update deduction_types
set fund_party_id = (select id from parties where kind = 'fund' order by created_at limit 1)
where fund_party_id is null and name ilike '%newmux reserve%';

alter table bank_accounts enable row level security;
alter table bank_reconciliations enable row level security;
alter table payouts enable row level security;
insert into schema_migrations (name) values ('0008_finance_core.sql');
commit;

-- ===== 0009_document_enums.sql =====
begin;
-- New document states and the credit-note type (Improvements PRD items 9, 10, 37).
-- Kept in their own migration: Postgres can't use an enum value in the same
-- transaction that adds it.
alter type document_status add value if not exists 'void';
alter type document_status add value if not exists 'declined';
alter type document_type add value if not exists 'credit_note';
insert into schema_migrations (name) values ('0009_document_enums.sql');
commit;

-- ===== 0010_documents.sql =====
begin;
-- Invoices & documents (Improvements PRD items 7–11, 37).

-- 8. The number a document had before NEWMUX OS (e.g. #00267, Quotation #2605).
alter table documents add column external_ref text;

-- 9. Void (with a reason) instead of delete; credit notes point at their invoice.
alter table documents add column void_reason text;
alter table documents add column voided_at timestamptz;
alter table documents add column credit_for_id uuid references documents(id) on delete set null;
create index idx_documents_credit_for on documents(credit_for_id) where credit_for_id is not null;

-- 11. More payment methods.
alter table payments drop constraint payments_method_check;
alter table payments add constraint payments_method_check
  check (method in ('cash', 'transfer', 'card', 'cheque', 'benefitpay', 'paypal', 'upwork', 'other'));

-- 10. Invoices no longer use the quote/contract states: an accepted or signed
--     invoice is simply sent (paid is derived from payments).
insert into document_status_history (document_id, from_status, to_status, changed_by)
select id, status, 'sent', null from documents where type = 'invoice' and status in ('accepted', 'signed');
update documents set status = 'sent', updated_at = now() where type = 'invoice' and status in ('accepted', 'signed');

-- 9. Demo invoices were "removed" by deleting their payments and archiving
--    them. An archived invoice with no payments at all is void, not revenue.
insert into document_status_history (document_id, from_status, to_status, changed_by)
select d.id, 'archived', 'void', null from documents d
where d.type = 'invoice' and d.status = 'archived' and not exists (select 1 from payments p where p.document_id = d.id);
update documents d
set status = 'void', voided_at = now(), updated_at = now(),
    void_reason = 'Archived with no payments recorded (test or demo data).'
where d.type = 'invoice' and d.status = 'archived' and not exists (select 1 from payments p where p.document_id = d.id);

-- 37. Every open quote gets a deal, so the pipeline carries its value.
create temporary table quote_deals as
select d.id as document_id, gen_random_uuid() as deal_id, d.client_id, d.status, d.total_cents, d.currency,
  d.created_by, d.project_id, d.accepted_at, d.created_at,
  coalesce((select li.description from document_line_items li where li.document_id = d.id order by li.sort_order limit 1),
           'Quote ' || d.document_number) as title
from documents d
where d.type = 'quote' and d.deal_id is null and d.status in ('draft', 'sent', 'accepted');

insert into deals (id, title, client_id, stage, value_cents, currency, probability, owner_id, project_id, won_at, closed_at, notes, created_by, created_at)
select deal_id, title, client_id,
  (case status when 'accepted' then 'won' when 'sent' then 'proposal' else 'qualified' end)::deal_stage,
  total_cents, currency,
  case status when 'accepted' then 100 when 'sent' then 50 else 25 end,
  created_by, project_id,
  case when status = 'accepted' then coalesce(accepted_at, now()) end,
  case when status = 'accepted' then coalesce(accepted_at, now()) end,
  'Created from its quote.', created_by, created_at
from quote_deals;

update documents d set deal_id = q.deal_id from quote_deals q where d.id = q.document_id;
drop table quote_deals;
insert into schema_migrations (name) values ('0010_documents.sql');
commit;

-- ===== 0011_hosting.sql =====
begin;
-- Hosting fees (Improvements PRD items 12–14).

-- 13. The client price can be unknown ("amount TBD"); services can be not started yet.
alter table hosting_subscriptions alter column amount_cents drop not null;
alter table hosting_subscriptions drop constraint hosting_subscriptions_status_check;
alter table hosting_subscriptions add constraint hosting_subscriptions_status_check
  check (status in ('active', 'overdue', 'paused', 'not_started'));

-- 14. What the service costs NEWMUX: a linked recurring expense, or a yearly cost.
alter table hosting_subscriptions add column recurring_expense_id uuid references recurring_expenses(id) on delete set null;
alter table hosting_subscriptions add column cost_per_year_cents bigint check (cost_per_year_cents >= 0);
alter table hosting_subscriptions add column cost_currency text check (cost_currency in ('BHD', 'USD'));

-- 12. Every invoice a hosting fee was billed on (not only the latest one).
alter table documents add column hosting_subscription_id uuid references hosting_subscriptions(id) on delete set null;
create index idx_documents_hosting on documents(hosting_subscription_id) where hosting_subscription_id is not null;
update documents d set hosting_subscription_id = h.id
from hosting_subscriptions h where h.linked_invoice_id = d.id and d.hosting_subscription_id is null;
insert into schema_migrations (name) values ('0011_hosting.sql');
commit;

-- ===== 0012_files.sql =====
begin;
-- Company files with expiry reminders (Improvements PRD items 18, 38).
-- Stored in Postgres so they are covered by the same backups and access rules
-- as everything else. Bytes live in file_blobs so listing files never loads them.

create table files (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'other'
    check (category in ('contract', 'registration', 'certificate', 'brand', 'legal', 'finance', 'receipt', 'other')),
  content_type text not null,
  size_bytes int not null,
  issue_date date,
  expiry_date date,
  remind_days_before int not null default 30 check (remind_days_before between 0 and 365),
  notes text,
  client_id uuid references clients(id) on delete set null,
  project_id uuid references projects(id) on delete set null,
  venture_id uuid references ventures(id) on delete set null,
  uploaded_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_files_expiry on files(expiry_date) where expiry_date is not null;

create table file_blobs (
  file_id uuid primary key references files(id) on delete cascade,
  data bytea not null
);

alter table files enable row level security;
alter table file_blobs enable row level security;
insert into schema_migrations (name) values ('0012_files.sql');
commit;

-- ===== 0013_expenses.sql =====
begin;
-- Expenses (Improvements PRD items 15, 16, 38).

-- 15. Venture spending.
alter table expenses add column linked_venture_id uuid references ventures(id) on delete set null;
alter table recurring_expenses add column linked_venture_id uuid references ventures(id) on delete set null;
create index idx_expenses_venture on expenses(linked_venture_id) where linked_venture_id is not null;

-- Expenses tagged "[Tbadel]" (or any venture's name or slug) in the text get the real link.
update expenses e set linked_venture_id = v.id from ventures v
where e.linked_venture_id is null
  and (position(lower('[' || v.name || ']') in lower(e.description)) > 0
    or position(lower('[' || v.slug || ']') in lower(e.description)) > 0);
update recurring_expenses r set linked_venture_id = v.id from ventures v
where r.linked_venture_id is null
  and (position(lower('[' || v.name || ']') in lower(r.name)) > 0
    or position(lower('[' || v.slug || ']') in lower(r.name)) > 0);

-- 16. Who paid: the company account (null) or a partner personally, who is then owed it back.
alter table expenses add column paid_by_party_id uuid references parties(id) on delete restrict;
alter table expenses add column reimbursement_status text not null default 'not_required'
  check (reimbursement_status in ('not_required', 'pending', 'reimbursed'));
alter table expenses add column reimbursement_payout_id uuid references payouts(id) on delete set null;
alter table recurring_expenses add column paid_by_party_id uuid references parties(id) on delete restrict;

-- 38. A photo of the receipt.
alter table expenses add column receipt_file_id uuid references files(id) on delete set null;
insert into schema_migrations (name) values ('0013_expenses.sql');
commit;

-- ===== 0014_housekeeping.sql =====
begin;
-- Housekeeping and UX data (Improvements PRD items 19, 21, 26, 31).

-- 19. The seeded demo account has no place in production.
delete from users where full_name = 'Demo Limited-Access User' and role = 'lead_dev';

-- 21. Notion migration: everything is done except the Vault and archiving Notion.
insert into app_settings (key, value) values (
  'notion_migration_checklist',
  '["Export client list from Notion", "Import clients and primary contacts", "Recreate open deals in the pipeline", "Move SOPs into the Wiki", "Re-enter open invoices and payments", "Move hosting fee schedule"]'::jsonb
)
on conflict (key) do update set value = (
  select coalesce(jsonb_agg(distinct step), '[]'::jsonb)
  from jsonb_array_elements_text(app_settings.value || excluded.value) as t(step)
), updated_at = now();

-- 31. A short name for lists ("Marasi" instead of "Marasi Alsawadi Resort & …").
alter table clients add column short_name text;

-- 26. "Snooze" on Today's Needs Attention items (key = kind:id).
create table attention_snoozes (
  key text primary key,
  until date not null,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table attention_snoozes enable row level security;
insert into schema_migrations (name) values ('0014_housekeeping.sql');
commit;

-- ===== Final check: no table may be readable through Supabase's public REST API =====
-- The app only ever talks to Postgres directly, as the table owner. Row level
-- security with no policies means the public API key can read or write nothing.
-- (db/migrations/0007_rls.sql does this too; repeating it covers every table.)
do $$
declare t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end $$;
