/**
 * Builds db/supabase-setup.sql: every file in db/migrations/ in one script, for
 * pasting into the Supabase SQL Editor when you can't run `npm run db:migrate`
 * (for example from a phone or tablet).
 *
 *   npm run db:supabase-sql
 *
 * Regenerate and commit the result whenever a migration is added. The script is
 * for a brand-new, empty database. Each migration runs in its own transaction
 * (db/migrations/0009 adds enum values that 0010 uses, which Postgres only
 * allows across a commit) and is recorded in schema_migrations, so the app's own
 * runner (`npm run db:migrate`) sees them as applied.
 */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const migrationsDir = path.join(root, "db", "migrations");
const outFile = path.join(root, "db", "supabase-setup.sql");

const files = fs
  .readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const parts: string[] = [
  `-- NEWMUX OS: database setup for a brand-new, empty Supabase project.
--
-- Generated by \`npm run db:supabase-sql\` from db/migrations/*.sql. Do not edit it
-- by hand; add a migration and regenerate instead.
--
-- Use: Supabase dashboard -> SQL Editor -> New query -> paste this whole file -> Run.
-- If the editor warns about a "destructive" query (migration 0010 drops a table
-- that was just created) choose "Run this query". Run it once, on an empty database.
-- It creates the tables only; the first login is created separately
-- (docs/DEPLOY_CLOUDFLARE.md, "Create your login").

create table if not exists schema_migrations (name text primary key, applied_at timestamptz not null default now());
`,
];

for (const file of files) {
  const sql = fs.readFileSync(path.join(migrationsDir, file), "utf8").trimEnd();
  parts.push(`-- ===== ${file} =====
begin;
${sql}
insert into schema_migrations (name) values ('${file}');
commit;
`);
}

parts.push(`-- ===== Final check: no table may be readable through Supabase's public REST API =====
-- The app only ever talks to Postgres directly, as the table owner. Row level
-- security with no policies means the public API key can read or write nothing.
-- (db/migrations/0007_rls.sql does this too; repeating it covers every table.)
do $$
declare t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end $$;
`);

fs.writeFileSync(outFile, parts.join("\n"));
console.log(`Wrote ${path.relative(root, outFile)} (${files.length} migrations).`);
